var tasks = [{"item":"Ring",
"id":-1,
"due":"Done!",
"responsible":"Dan",
"completed":"yes",
"prize":"no",
"details":null,
"chained":null
},
{"item":"Get Engaged",
"id":0,
"due":"Done!",
"responsible":"Dan",
"completed":"yes",
"prize":"no",
"details":null,
"chained":null
},
{"item":"Pick Date",
"id":1,
"due":"Done!",
"responsible":"Dan + Whit",
"completed":"yes",
"prize":"no",
"details":null,
"chained":null
},
{"item":"Location",
"id":2,
"due":"Done!",
"responsible":"Dan + Whit",
"completed":"yes",
"prize":"no",
"details":null,
"chained":null
},
{"item":"Venue for Ceremony",
"id":3,
"due":"Done!",
"responsible":"Dan",
"completed":"yes",
"prize":"no",
"details":null,
"chained":null
},
{"item":"Venue for Reception",
"id":4,
"due":null,
"responsible":null,
"completed":"no",
"prize":"no",
"details":null,
"chained":null
},
{"item":"Select Wedding Party",
"id":5,
"due":null,
"responsible":null,
"completed":"no",
"prize":"no",
"details":null,
"chained":null
},
{"item":"Guest List",
"id":6,
"due":null,
"responsible":null,
"completed":"no",
"prize":"no",
"details":null,
"chained":null
},
{"item":"Catering",
"id":7,
"due":null,
"responsible":null,
"completed":"no",
"prize":"no",
"details":null,
"chained":null
},
{"item":"Premarital Counceling",
"id":8,
"due":null,
"responsible":null,
"completed":"no",
"prize":"no",
"details":null,
"chained":null
},
{"item":"Engagement Photos",
"id":9,
"due":null,
"responsible":null,
"completed":"no",
"prize":"no",
"details":null,
"chained":null
},
{"item":"Work out Regimen/Diet",
"id":10,
"due":null,
"responsible":null,
"completed":"no",
"prize":"no",
"details":null,
"chained":null
},
{"item":"Save the Dates",
"id":11,
"due":null,
"responsible":null,
"completed":"no",
"prize":"no",
"details":null,
"chained":null
},
{"item":"To Do Site",
"id":12,
"due":"done!",
"responsible":"Dan",
"completed":"yes",
"prize":"no",
"details":null,
"chained":null
},
{"item":"Get addresses",
"id":13,
"due":null,
"responsible":null,
"completed":"no",
"prize":"no",
"details":null,
"chained":null
},
{"item":"Invitations",
"id":14,
"due":null,
"responsible":null,
"completed":"no",
"prize":"no",
"details":null,
"chained":null
},
{"item":"Photographer",
"id":15,
"due":null,
"responsible":null,
"completed":"no",
"prize":"no",
"details":null,
"chained":null
},
{"item":"Videographer",
"id":16,
"due":null,
"responsible":null,
"completed":"no",
"prize":"no",
"details":null,
"chained":null
},
{"item":"Flowers",
"id":17,
"due":null,
"responsible":null,
"completed":"no",
"prize":"no",
"details":null,
"chained":null
},
{"item":"Wedding Bands",
"id":18,
"due":null,
"responsible":null,
"completed":"no",
"prize":"no",
"details":null,
"chained":null
},
{"item":"Honeymoon Location",
"id":19,
"due":null,
"responsible":null,
"completed":"no",
"prize":"no",
"details":null,
"chained":null
},
{"item":"Honeymoon Flights",
"id":20,
"due":null,
"responsible":null,
"completed":"no",
"prize":"no",
"details":null,
"chained":null
},
{"item":"Honeymoon Hotels",
"id":21,
"due":null,
"responsible":null,
"completed":"no",
"prize":"no",
"details":null,
"chained":null
},
{"item":"Registry",
"id":22,
"due":null,
"responsible":null,
"completed":"no",
"prize":"no",
"details":null,
"chained":null
},
{"item":"Wedding Website",
"id":23,
"due":null,
"responsible":null,
"completed":"no",
"prize":"no",
"details":null,
"chained":null
},
{"item":"Night-of Hotel (W?)",
"id":24,
"due":null,
"responsible":null,
"completed":"no",
"prize":"no",
"details":null,
"chained":null
},
{"item":"Bachelor Party",
"id":25,
"due":null,
"responsible":null,
"completed":"no",
"prize":"no",
"details":null,
"chained":null
},
{"item":"Bachelorette Party",
"id":26,
"due":null,
"responsible":null,
"completed":"no",
"prize":"no",
"details":null,
"chained":null
},
{"item":"Move out of 1233 G Street",
"id":27,
"due":"December 31, 2016",
"responsible":"Dan",
"completed":"no",
"prize":"no",
"details":null,
"chained":null
},
{"item":"Vows",
"id":28,
"due":null,
"responsible":null,
"completed":"no",
"prize":"no",
"details":null,
"chained":null
},
{"item":"Music",
"id":29,
"due":null,
"responsible":null,
"completed":"no",
"prize":"no",
"details":null,
"chained":null
},
{"item":"Contraception",
"id":30,
"due":"Jan 14, 2016",
"responsible":"Whitney",
"completed":"no",
"prize":"sex",
"details":null,
"chained":null
},
{"item":"Get Hitched",
"id":31,
"due":"Jan 14, 2016",
"responsible":"Bo + God + Dan + Whitney",
"completed":"no",
"prize":"sex",
"details":null,
"chained":null
},
{"item":"Last To Do: Each Other",
"id":32,
"due":"Jan 14, 2016",
"responsible":"Dan + Whitney",
"completed":"no",
"prize":"yes",
"details":null,
"chained":null
}]